version: '3'  # version of compose format 

services:
  laptop-service:
    build: ./server  
    volumes:
      - ./server:/usr/src/app 
    ports:
      - 5000:5000  # host:container

  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5001:80  # host:container
    depends_on:
      - laptop-service  # website is not going to work unless laptop-service is running

  mongodb:
    image: mongo:3.0.2
    ports:
      - "27017:27017"
